### ISSUE TITLE
Cannot run after succeful build

### ISSUE THREAD

**Issue by Ygarr** [raydac/zxpoly#2]
After successful building error while launching emul from `zxpoly/zxpoly-emul/target` directory:
`java -jar zxpoly-emul-2.0.5-SNAPSHOT.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang3/SystemUtils
	at com.igormaznitsa.zxpoly.Application.main(Application.java:58)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.SystemUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 1 more
`

Also size of zxpoly-emul-2.0.5-SNAPSHOT.jar 483,0 kB 
and size of full working jar (zxpoly-emul.jar) is 3,9 MB

**Comment by raydac** [comment]
shade plugin was situated in publish profile, I have moved it to regular build process so that now you can get fat jar

**Comment by raydac** [comment]
@Ygarr now it works well?

**Comment by Ygarr** [comment]
Yes, thanks a lot
